services:
  postgres:
    image: postgres:16-alpine
    container_name: th_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: th
      POSTGRES_PASSWORD: th
      POSTGRES_DB: thplatform
    ports:
      - "5432:5432"
    volumes:
      - th_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U th -d thplatform"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: th_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - th_redis_data:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: th_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI http://localhost:8025

volumes:
  th_pg_data:
  th_redis_data:
