// Placeholder. Real UI to be generated by Claude Design (see docs/
// PROMPTS-*.md prompt #5) and pasted here. Keeps the app runnable
// until then.
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";

export default function LoginPage() {
  const { t } = useTranslation();
  return (
    <div className="flex h-screen w-screen items-center justify-center bg-canvas text-fg">
      <div className="w-[380px] rounded-xl border border-border bg-surface-raised p-8 shadow-md">
        <h1 className="font-display text-[28px] font-bold">{t("auth.login")}</h1>
        <p className="mt-2 text-sm text-fg-muted">
          {t("app.name")} — {t("app.tagline")}
        </p>
        <p className="mt-8 text-xs text-fg-subtle">
          [ Claude Design will replace this with the real login screen. Prompt lives in{" "}
          <code>docs/05-prompts-claude-design.md #5</code>. ]
        </p>
        <p className="mt-6 text-sm">
          <Link to="/register" className="text-brand hover:underline">
            {t("auth.register")}
          </Link>
        </p>
      </div>
    </div>
  );
}
